# version: "3.9"

# services:
#   mysql:
#     image: mysql:8.0
#     container_name: mysql_db
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: rootpassword
#       MYSQL_DATABASE: Billing
#       MYSQL_USER: appuser
#       MYSQL_PASSWORD: apppassword
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql
#       - ./init.sql:/docker-entrypoint-initdb.d/init.sql

#   backend:
#     build: .
#     container_name: node_backend
#     restart: always
#     ports:
#       - "3000:3000"
#     env_file:
#       - .env
#     depends_on:
#       - mysql

# volumes:
#   mysql_data:




version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: billing_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    image: student2027/nimaran:latest
    container_name: node_backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mysql

volumes:
  mysql_data:
